### ISSUE TITLE
Adicionar uma nova rede social (Twitter)?

### ISSUE THREAD

**Issue by ftonato** [filipedeschamps/javascriptmasters.com.br#101]
Beleza Filipe?

Ao terminar de ler a última postagem no blog, percebi que sugeres que sigamos às contas do Youtube e Facebook, mas já pensou em criar um Twitter?

Você podia agendar as postagens (tweets) p/ lá, com os links das postagens do blog!

Lembre-se que algumas pessoas não usam Facebook, eu me incluo nessa lista!

Bom, é apenas uma dica!

Abraço!

**Comment by filipedeschamps** [comment]
@ftonato tudo bem meu caro?

Acho uma idéia ótima! Eu só preciso ver alguma forma de automatizar este feed, para que não acrescente uma rotina a mais.

Como poderíamos fazer isto automatizado?

**Comment by ftonato** [comment]
@filipedeschamps tudo tranquilo e por aí?

Como tu estás agendando as postagens do blog hoje?
Poderíamos criar uma rotina para que  ao publicar uma nova postagem, ele faça um tweet com o título e a url...
E também adicionar o botão para quem está lendo (no site), "tuitar".

**Comment by filipedeschamps** [comment]
Fala meu caro, voltando ao assunto!

Hoje as postagem são um push neste repositório para a branch `gh-pages`, não tem periodicidade. O sistema que utilizo é o Jekyll e ele fornece RSS, veja: https://www.javascriptmasters.com.br/feed.xml

Você recomenda algum automatizador que pudesse ficar lendo esse RSS e postar no Twitter cada post novo?

**Comment by ftonato** [comment]
Eu havia visto alguns enquanto navegava dias atrás, vou deixar alguns links aqui abaixo:

[Twitter Feed](http://twitterfeed.com)
[Twibble](https://twibble.io/)

Ouvi dizer que dá para fazer com o [Hootsuite](https://hootsuite.com/pt-br/), mas não encontrei um tutorial...

Você que decide, fico no aguardo :+1:

**Comment by ftonato** [comment]
@filipedeschamps Estive olhando aqui, tem algo que nos pode ser útil, o [IFTTT](https://ifttt.com)!

Podemos criar a receita lá, seguindo essa lógica:
Quando existir um "new feed item", então "post a tweet"!

Podemos configurar o texto padrão para algo do tipo:
````
{{EntryTitle}}
via [arroba]twitter_do_javascriptmasters
{{EntryUrl}}
````

**Comment by filipedeschamps** [comment]
Opa, eu topo! E @ftonato eu te adicionei como colaborador do projeto, agora você pode dar push direto se eu não me engano, não sei exatamente como esta parte do Github funciona ainda mas vamos descobrir :+1:

**Comment by ftonato** [comment]
Blz, te chamo no e-mail p/ tirar umas dúvidas!

**Comment by ftonato** [comment]
Já temos a conta no Twitter, precisamos definir, se iremos mudar o e-mail que eu cadastrei p/ criarmos a conta do IFTTT com o e-mail correto, certo?

**Comment by filipedeschamps** [comment]
Opa!! Eu topo utilizar o email javascriptmasters@gmail.com que *por enquanto* é o email base.

Mais para frente vamos fazer um contato@javascriptmasters.com.br :)

**Comment by ftonato** [comment]
@filipedeschamps Vai alterar no twitter para o que você usa?
Tu podes fazer o cadastro no IFTTT com esse email? Para criarmos a 'receita' e testar o/

**Comment by filipedeschamps** [comment]
Boa, consigo sim! Dai te passo o acesso :)

Faço isos hoje a noite!

**Comment by ftonato** [comment]
Criado "receita" com padrão:
````
{{EntryTitle}}
{{EntryUrl}}
````
Agora, basta que haja um novo item no feed, e um tweet será disparado!

**Comment by ftonato** [comment]
Deixamos a issue aberta, até que haja uma nova postagem no blog, e se tudo acontecer como esperado, encerramos a issue, certo? :dancers:

**Comment by filipedeschamps** [comment]
Sen-sa-ci-o-nal :)

Já tem post no forno, acho que até este final de semana eu consigo publicar
:)

2015-07-29 22:44 GMT-03:00 Ademílson F. Tonato <notifications@github.com>:

**Comment by ftonato** [comment]
Alterado a "receita" para o padrão:
````
{{EntryTitle}}
{{EntryUrl}}
#javascript
````

Aguardando a postagem, para confirmar funcionamento. :smile:

**Comment by filipedeschamps** [comment]
Vai funcionar e vai ficar top :+1:

**Comment by filipedeschamps** [comment]
![image](https://cloud.githubusercontent.com/assets/4248081/9036877/0f2de9ca-39bc-11e5-8948-0f9be01fcb81.png)

hahahah sensacional!!!!!!

**Comment by ftonato** [comment]
Legal :clap: o/
Mais alguma melhora a ser feita na "receita" do IFTTT ou podemos fechar a issue?

**Comment by filipedeschamps** [comment]
Por mim já está excelente e podemos fechar!!! :)

Se precisarmos, mais para frente abrimos uma outra issue, o que acha?

2015-08-03 8:53 GMT-03:00 Ademílson F. Tonato <notifications@github.com>:

**Comment by ftonato** [comment]
Certo ;)

**Comment by ftonato** [comment]
12
