### ISSUE TITLE
Fazer testes de audio com o novo lapela (incluindo edição do audio)

### ISSUE THREAD

**Issue by filipedeschamps** [filipedeschamps/javascriptmasters.com.br#102]

**Comment by filipedeschamps** [comment]
Fiz os testes com o novo lapela, mas como esperado, por ele ser muito barato o audio até que ficou ok na primeira gravação, mas os vídeos seguintes saíram completamente sem audio :(

Me ferrei, vou ter que gastar uma grana legal agora em um novo lapela :+1:

**Comment by ftonato** [comment]
Triste realidade :/
