### ISSUE TITLE
Ação "hover" dos botões!

### ISSUE THREAD

**Issue by ftonato** [filipedeschamps/javascriptmasters.com.br#108]
Adicionar a ação de `:hover` dos botões:
"Assine a newsletter";
"Assinar newsletter";
"Fechar".

**Comment by filipedeschamps** [comment]
Sensacional meu caro, feito merge :+1:

**Comment by filipedeschamps** [comment]
E casou com 700 subscribers no canal do Youtube :)

**Comment by ftonato** [comment]
Vamos chegar aos 1000 o/
