### ISSUE TITLE
Fazer a capa do canal do Youtube

### ISSUE THREAD

**Issue by filipedeschamps** [filipedeschamps/javascriptmasters.com.br#111]
Devido ao número de subscribers ter passado de 500, o Youtube liberou uma URL customizada para o canal, que obviamente escolhi https://www.youtube.com/c/JavascriptMasters

Mas agora estou precisando de ajuda para fazer uma capa mais legal para o canal, pois por enquanto está o amarelo do Javascript.

Alguém me ajuda? :+1:

**Comment by forsureitsme** [comment]
Fiz um padrão, baseado no símbolo do YingYang que está no ícone. Ainda não é uma solução ideal, mas me parece melhor que o fundo amarelo. Colocar algum dizer em preto sobre este padrão talvez fique melhor...

![pattern](https://cloud.githubusercontent.com/assets/2235293/8964229/c86b8f70-35fa-11e5-9634-0ee4f482fa36.png)

**Comment by filipedeschamps** [comment]
@forsureitsme que sensacional!!!! Muito obrigado pela contribuição, achei excelente!

Tentei fazer o upload para o canal, porém o Youtube pediu uma imagem maior, veja:


![image](https://cloud.githubusercontent.com/assets/4248081/8964642/1e657c18-35fd-11e5-9a64-38a168d354ad.png)

**Comment by forsureitsme** [comment]
Neste caso:
![photo 2](https://cloud.githubusercontent.com/assets/2235293/8965803/276d587e-3604-11e5-9533-5d1778c408ef.png)

**Comment by filipedeschamps** [comment]
Sensacional!!!

Olha lá como ficou! :+1:

**Comment by ftonato** [comment]
Muito obrigado @forsureitsme ;)

@filipedeschamps Issue resolvida?

**Comment by filipedeschamps** [comment]
Issue resolvidíssima! Matamos a pau galera :+1:

**Comment by filipedeschamps** [comment]
@forsureitsme e @ftonato mandei uma newsletter agradecendo vocês :+1: 

Cópia do texto que foi enviado:
http://eepurl.com/buTsKr

**Comment by ftonato** [comment]
@filipedeschamps Sensacional mestres!
Não há de que agradecer, lembre-se que ninguém contribuiria se você não tivesse pensado em criar o projeto Open Source! :+1:

**Comment by filipedeschamps** [comment]
Massa :+1:
