### ISSUE TITLE
Consertar menu em versão Mobile

### ISSUE THREAD

**Issue by filipedeschamps** [filipedeschamps/javascriptmasters.com.br#113]
Hoje em desktop, o usuário consegue clicar no logo do JS Masters para voltar para home, e também clicar no link Mindulness para ver os posts desta categoria.

Porém no mobile, existe apenas o logo (e que leva o usuário para a home), ou seja, ele nunca vai conseguir entrar em https://www.javascriptmasters.com.br/blog/

*E escrevendo isso que notei agora que o link Mindulness não está levando para https://www.javascriptmasters.com.br/blog/mindfulness/*

Talvez uma das abordagens seja, no mobile, manter ainda só o logo mas levar diretamente para o /blog

**Comment by ftonato** [comment]
Podes deixar que eu arrumo isso hoje :)

Me surgiu uma dúvida, qual a diferença entre às páginas [/blog/](https://www.javascriptmasters.com.br/blog/)  e  [/blog/mindfulness/](https://www.javascriptmasters.com.br/blog/mindfulness/), pois até então parecem ter o mesmo conteúdo, está correto isso?

**Comment by filipedeschamps** [comment]
Show!! E excelente pergunta!

Eu até agora não fui claro quanto a organização dos temas, o que imagino é o seguinte:

O blog terá basicamente 3 categorias:

**Mindfulness**
Fala sobre *O Desenvolvedor* como pessoa, sobre sua conduta.

**Teoria**
Tudo que envolve a teoria da programação, como por exemplo design patterns.

**Prática**
Colocar a mão na massa, código. Quero também fazer review do código fonte de outras bibliotecas para aprender com elas.

Então hoje de fato não haverá diferença entre o /blog/ ou /blog/mindfulness, pois só tem uma categoria :)  mais para frente vai ficar bem massa!

**Comment by ftonato** [comment]
Ah legal o/

Bom, então eu arrumarei o link também ;)

**Comment by filipedeschamps** [comment]
Show!

**Comment by ftonato** [comment]
@filipedeschamps O que tu achas melhor no mobile, levar direto para /blog ou aparecer o link do /blog/mindfulness para ele acessar (como mostra a imagem abaixo)?

![rsz_captura_de_tela_de_2015-07-30_201407](https://cloud.githubusercontent.com/assets/5417662/8997461/fb15ec6a-36f7-11e5-8f4a-0ca4503a25b1.png)

**Comment by filipedeschamps** [comment]
Interessante abordagem meu caro!

Voce me deu uma ideia otima! Sabe a versao do logo ícone que mostra no
desktop? O que acha de colocar ele alinhado a esquerda e "Blog" alinhado a
direita? Pois dai nao tem como nao entender que clicar ali volta para o
blog.

Faz sentido?

**Comment by ftonato** [comment]
Faz todo sentido, e na minha opinião, mantém a "consistência"!

![rsz_captura_de_tela_de_2015-07-30_211226](https://cloud.githubusercontent.com/assets/5417662/8998160/4c58a4b6-3700-11e5-8489-b72b859392a9.png)
**OBS:** O logo ficou "aberto" pois eu estava com o mouse sobre ele.

**Comment by filipedeschamps** [comment]
Cara, sensacional!!!

Se quiser, pode fazer o pull request e já fazer o merge por conta própria,
fica a vontade.

Se der problema de permissão, vamos investigar aqui como liberar.

**Comment by ftonato** [comment]
Fiz o pull request e o merge!
Confirma se está tudo certo, por favor?

**Comment by filipedeschamps** [comment]
Cara ficou fantástico, tudo 100%!!!!!! Matou a pau :)

**Comment by ftonato** [comment]
Uhull :dancers:
