### ISSUE TITLE
Criar email com domínio "javascriptmasters.com.br"

### ISSUE THREAD

**Issue by filipedeschamps** [filipedeschamps/javascriptmasters.com.br#121]
E atrelar ao Mailchimp para melhorar a entrega da Newsletter.

Alguns usuários estão reportando que ela está caindo na caixa de spam.

**Comment by ftonato** [comment]
Adicionar também esse e-mail para a conta do Twitter.

**Comment by filipedeschamps** [comment]
Falta só o Google reconhecer o domínio e dai teremos o contato@javascriptmasters.com.br :+1:

**Comment by ftonato** [comment]
o/

**Comment by filipedeschamps** [comment]
Reconhecido :+1: 

@ftonato a senha é aquela mesma do email (aquela que usei a sua como base, lembra?)

**Comment by filipedeschamps** [comment]
Configurado no Mailchimp e adicionado os records necessários no DNS do domínio. Agora o email chega como se fosse enviado pelo javascriptmasters.com.br e não pelo mailchimp em nosso nome. 

![image](https://cloud.githubusercontent.com/assets/4248081/9274127/414acac6-4269-11e5-925c-2373fcffe1fd.png)

:+1:

**Comment by ftonato** [comment]
o/
Vou alterar os dados do Twitter e do IFTTT e te aviso por e-mail!

**Comment by ftonato** [comment]
Alterei o e-mail no Twitter e no IFTTT, provavelmente precisará confirmar, podes fazer isso?

@filipedeschamps

**Comment by filipedeschamps** [comment]
Confirmado! O IFTTT acabou não pedindo para confirmar o email, lembro que ele não mandou confirmação na primeira vez quando a conta foi criada.

Em paralelo, alterei a senha do Twitter para aquela sem o underscore, ok?

**Comment by ftonato** [comment]
Certo, sem problemas, vou alterar aqui no TweetDeck p/ eventuais postagens ;)
