### ISSUE TITLE
Agendar Tweets das postagens antigas!

### ISSUE THREAD

**Issue by ftonato** [filipedeschamps/javascriptmasters.com.br#128]
Agendar tweets das postagens antigas (1 tweet por dia), da url do canal (1 tweet por dia);
Fazer esses agendamentos manuais, pois o IFTTT não fará essas postagens!

@filipedeschamps pode deixar que eu faço isso hoje à noite :+1:

**Comment by filipedeschamps** [comment]
Caramba excelente ideia!!!! :)

**Comment by ftonato** [comment]
**Vou deixar aqui pronto, só copiar e agendar depois!**

Por que o nome Javascript Masters?
https://www.javascriptmasters.com.br/blog/mindfulness/por-que-o-nome-javascript-masters/
#javascript

O que é mindfulness?
https://www.javascriptmasters.com.br/blog/mindfulness/o-que-e-mindfulness/
#javascript

Como ter superpoderes na programação 
https://www.javascriptmasters.com.br/blog/mindfulness/como-ter-superpoderes-na-programacao/
#javascript

Melhor aplicativo para meditação 
https://www.javascriptmasters.com.br/blog/mindfulness/melhor-aplicativo-para-meditacao/
#javascript

3 dicas simples para tratamento de ansiedade 
https://www.javascriptmasters.com.br/blog/mindfulness/3-dicas-para-tratamento-de-ansiedade/
#javascript

10 coisas que todo desenvolvedor babaca fala 
https://www.javascriptmasters.com.br/blog/mindfulness/10-coisas-que-todo-desenvolvedor-babaca-fala/
#javascript

O que é ser um desenvolvedor sênior? 
https://www.javascriptmasters.com.br/blog/mindfulness/o-que-e-ser-um-desenvolvedor-senior/
#javascript

Engenharia vs Engenhoca 
https://www.javascriptmasters.com.br/blog/mindfulness/engenharia-vs-engenhoca/
#javascript

**Comment by ftonato** [comment]
Já temos o endereço do youtube com o nome do canal (youtube.com/channel/**nome_do_canal**) ou ainda estamos usando essa url (**youtube.com/channel/UCU5JicSrEM5A63jkJ2QvGYw**)?

**Comment by ftonato** [comment]
**Vou deixar aqui pronto, só copiar e agendar depois! (continuação)**

Já conhece nosso Facebook?
https://www.facebook.com/javascriptmasters
#javascript

**Comment by filipedeschamps** [comment]
Ja temos! Ficou assim: https://www.youtube.com/c/JavascriptMasters

**Comment by ftonato** [comment]
Beleza, valeu :)

**Vou deixar aqui pronto, só copiar e agendar depois! (continuação)**

Já conhece nosso canal no youtube?
https://www.youtube.com/c/JavascriptMasters
#javascript

**Comment by ftonato** [comment]
Agendei um tweet por dia, que começa amanhã, com às postagens do blog e deixei agendado também, tweets aleatórios com a url do Facebook e do Youtube!

**Comment by filipedeschamps** [comment]
Matou a pau :+1:
