### ISSUE TITLE
Automatizar tarefas (Mídias Sociais)

### ISSUE THREAD

**Issue by ftonato** [filipedeschamps/javascriptmasters.com.br#129]
Já que usamos o IFTTT para automatizar a tarefa de 'tuitar', poderíamos adicionar essa mesma tarefa para publicações no Facebook.

O que achas? *(Eu não entendo muito, já que não tenho Facebook a um longo tempo :p)*
/cc @filipedeschamps

**Comment by filipedeschamps** [comment]
Poxa eu topo! Agora que sabemos que o RSS funciona, topo sim! :)

**Comment by ftonato** [comment]
Essa vou deixar para você configurar, já que eu não entendo nada de Facebook e nem a senha tenho haha

Se quiser que eu crie, é só me avisar e mandar a senha por e-mail o/

**Comment by filipedeschamps** [comment]
Agora ferrou, porque eu também não sei fazer hahaha pelo que entendo, a
página não tem senha. Você precisa criar uma conta no facebook e eu posso
lhe adicionar como dono da página, mas mesmo assim isso não soluciona o
problema, pois vai ser um robô que vai fazer a atualização e ele precisa
ter acesso.

Ao menos eu acho que é isso. Vou ver aqui como gera essa autorização!

2015-08-14 22:59 GMT-03:00 Ademílson F. Tonato <notifications@github.com>:

**Comment by ftonato** [comment]
Alguma novidade sobre essa issue? @filipedeschamps

**Comment by ftonato** [comment]
Podemos abrir novamente a _issue_ se necessário.

Fico a disposição!
