### ISSUE TITLE
Parabéns \o/

### ISSUE THREAD

**Issue by ftonato** [filipedeschamps/javascriptmasters.com.br#132]
````javascript
function quantidadeDeInscritos() {
  return 800;
};
quantidadeDeInscritos(); //800
````

Só queria deixar os parabéns pelo trabalho, Mestre @filipedeschamps o/

**Comment by filipedeschamps** [comment]
ahhahhhaha sen-sa-ci-o-nal meu caro, valeu!!!

Essa semana quero escrever o post introdutório da categoria **Teoria** :+1:

**Comment by ftonato** [comment]
Legal, fico no aguardo!
Manda spoiler haha

**Comment by filipedeschamps** [comment]
ahahaha vai ser bem simples, mas é um post importante. É o que falou na categoria mindfulness :)

**Comment by ftonato** [comment]
Nada é tão simples que não possa servir de aprendizado para alguém!

**Comment by filipedeschamps** [comment]
Boaaaa!!

2015-08-17 22:06 GMT-03:00 Ademílson F. Tonato <notifications@github.com>:
