### ISSUE TITLE
Mailchimp enviado SPAM!

### ISSUE THREAD

**Issue by ftonato** [filipedeschamps/javascriptmasters.com.br#145]
Continuo a receber **SPAM** dos e-mails que são enviados pelo Mailchimp!

Sugiro verificar com mais alguns usuários cadastrados na newsletter se o problema continua!

**Comment by filipedeschamps** [comment]
Puts que pena!

Você tem um print para eu ver como ele está mostrando o cabeçalho?

2015-09-02 16:28 GMT-03:00 Ademílson F. Tonato <notifications@github.com>:

**Comment by ftonato** [comment]
Não sei onde meus e-mails estão se escondendo, pois não achei =(

**Comment by filipedeschamps** [comment]
ahahah fechado! Bom, no próximo vamos analisar em detalhes :+1:

**Comment by ftonato** [comment]
Certo, ficamos no aguardo!

**Comment by ftonato** [comment]
![imageedit_2_4071334213](https://cloud.githubusercontent.com/assets/5417662/9863678/83627720-5b18-11e5-8ada-317bf43d3700.jpg)
Segue em spam como havia comentado :(

**Comment by filipedeschamps** [comment]
Que bizarro @ftonato o cabeçalho está ok, o Mailchimp está enviando com a assinatura correta. Puts não sei porque isto está acontecendo :(

Este Outlook é versão web ou desktop?

**Comment by ftonato** [comment]
@filipedeschamps eu uso o Client do Thunderbird p/ Linux ;)

**Comment by ftonato** [comment]
Isso é o que aparece quando eu uso o cliente do Outlook web:

![error](https://cloud.githubusercontent.com/assets/5417662/9865453/07913de2-5b2d-11e5-88e5-50ca0de4da5e.png)
Marquei agora como confiável, vamos ver o que acontecerá com o próximo e-mail que eu receber...

**Comment by filipedeschamps** [comment]
Boa, fechado :)

**Comment by ftonato** [comment]
Não sei se foi o fato de eu ter marcado como confiável, mas dessa vez ele não foi para o SPAM!
Talvez fosse interessante você tirar a dúvida com algumas outras pessoas p/ ver se mais alguém ainda está recebendo e-mail como SPAM...

**Comment by filipedeschamps** [comment]
@ftonato o último email veio normal também?

**Comment by ftonato** [comment]
@filipedeschamps sim o/

**Comment by filipedeschamps** [comment]
Show! Então vou fechar esta issue por hora, mas com certeza vamos reabrir uma novo futuro com novos casos :+1:
