### ISSUE TITLE
Incluir Github no footer de todos os layouts

### ISSUE THREAD

**Issue by filipedeschamps** [filipedeschamps/javascriptmasters.com.br#147]
Tem algumas páginas que estão sem include do footer.

**Comment by ftonato** [comment]
Olhando rapidamente, encontrei essas três da lista, encontrou mais alguma?

* [Home](https://www.javascriptmasters.com.br/)
* [Mindfulness](https://www.javascriptmasters.com.br/blog/mindfulness/)
* [Teoria](https://www.javascriptmasters.com.br/blog/teoria/)

**Comment by filipedeschamps** [comment]
Sensacional, acho que não foge disso!
