### ISSUE TITLE
Remover o script do Inspectlet

### ISSUE THREAD

**Issue by filipedeschamps** [filipedeschamps/javascriptmasters.com.br#160]
Ele serve para gravar a tela do usuário navegando pelo site. Foi um teste legal, mostra o heatmap, dá para notar até que altura do artigo os leitores estão indo, mas fora isto, não estou utilizando os resultados para nada :)

Vamos remover para contribuir com o load.

**Comment by ftonato** [comment]
Como foram os resultados?

**Comment by filipedeschamps** [comment]
Foi bem interessante, um dos padrões que detectei foi que as pessoas primeiro fazem uma rápida leitura dinâmica (talvez para ler os subtítulos e aquelas frases grandes) e depois decidem se vão ler ou não o artigo. Então é muito importante que tenham estes itens para a pessoa utilizar como âncora :+1:

**Comment by ftonato** [comment]
Legal :+1: 

E a ferramenta gerava *logs* em formato de vídeo?

**Comment by filipedeschamps** [comment]
Isso, o formato não é vídeo, pois ele remonta o DOM, mas o efeito final é
como se fosse um vídeo :)

**Comment by ftonato** [comment]
Ah entendi! Legal :+1:
