### ISSUE TITLE
Minificar CSS e comprimir as imagens

### ISSUE THREAD

**Issue by ftonato** [filipedeschamps/javascriptmasters.com.br#161]
Estava navegando agora quando percebi que o CSS não está minificado e as imagens não estão comprimidas.

O que acha de adicionarmos essas rotinas, para melhorar a performance e desempenho do site?

**Comment by filipedeschamps** [comment]
Boa!!!

Como será que conseguimos fazer isso uma rotina que o Github possa rodar?
Pois ele hoje faz o build automático.

**Comment by ftonato** [comment]
Acho que isso pode ajudar:

* Sobre minificar o [CSS](http://markdotto.com/2014/09/25/sass-and-jekyll/#minification);
* Sobre comprimir as [imagens e qualquer outro asset-pipeline](https://github.com/matthodan/jekyll-asset-pipeline)

**Comment by filipedeschamps** [comment]
Hmmm muito interessante o primeiro link do CSS, ainda mais por ser nativo do Jekyll.

O segundo pelo que vi não dá para deixar o Github fazer o build, mas talvez podemos entregar os estáticos buildados. De qualquer forma, vamos fazer o primeiro com certeza!

**Comment by ftonato** [comment]
Beleza!
Eu imagino que não irão ter muitas mais imagens, pois elas "devem" aparecer em postagens eventuais (o parâmetro que usei para dizer isso são as próprias postagens), então comprimindo as atuais já teríamos uma grande diferença!

**Comment by filipedeschamps** [comment]
sass comprimido :+1:

**Comment by ftonato** [comment]
:dancers: 
Vamos comprimir as imagens que temos até agora de forma manual, até implementar algo para comprimir?

**Comment by filipedeschamps** [comment]
Eu voto sempre pela automatização! Precisamos estudar como casar o build remoto do Github com o build local, pois o remoto não aceita nenhum plugin (ou parece que tem uma lista fixa bem pequena).

**Comment by ftonato** [comment]
Eu concordo =)
E se adicionarmos grunt ou gulp p/ automatizar as tarefas necessárias? *(No nosso caso atual, minificação de imagens)*

**Comment by filipedeschamps** [comment]
Eu gosto **muito** do Gulp, mas não me agrada adicionar uma dependência desta que é em Node em um projeto que é em Ruby, principalmente pelo fato do Jekyll ser (ou ter que ser kkk) autosuficiente. Faz sentido?

**Comment by ftonato** [comment]
Faz total sentido!

**Comment by filipedeschamps** [comment]
Usei aquele tinypng online para otimizar o que temos hoje por enquanto :)

![image](https://cloud.githubusercontent.com/assets/4248081/10417295/a5fcb7ba-700c-11e5-9aeb-d5518796904a.png)

**Comment by ftonato** [comment]
:+1:
