### ISSUE TITLE
Adicionar um editor config

### ISSUE THREAD

**Issue by ftonato** [filipedeschamps/javascriptmasters.com.br#166]
O que acha de adicionarmos um arquivo de "configurações do editor" p/ mantermos um padrão?
Sugiro o execelente [EditorConfig](http://editorconfig.org), o que você acha?

//cc @filipedeschamps

**Comment by filipedeschamps** [comment]
Opa! Eu topo, vamos fazer :+1:

**Comment by ftonato** [comment]
Tens algum que você já esteja usando e ache válido p/ esse projeto?

**Comment by filipedeschamps** [comment]
Hoje utilizo o .vimfiles do Pedro Franceschi https://github.com/pedrofranceschi/vimfiles

Meio que traz um *editor config*, mas não é como os tradicionais. Hoje não teria nenhuma sugestão fora esse vimfiles do Pedro :)

**Comment by ftonato** [comment]
Podemos utilizar esse? *Sugestão*

````
; top-most EditorConfig file
root = true

; Unix-style newlines with a newline ending every file
[*]
end_of_line = lf
insert_final_newline = true
indent_style = space
indent_size = 2
charset = utf-8
trim_trailing_whitespace = true
````

Podemos talvez fazer uma configuração diferente para os arquivos .md
````
[*.md]
trim_trailing_whitespace = false
````
