### ISSUE TITLE
Produzir vídeo: Nova categoria: Teoria

### ISSUE THREAD

**Issue by filipedeschamps** [filipedeschamps/javascriptmasters.com.br#169]
Agora com a última gravação vai ficar top :+1:

**Comment by filipedeschamps** [comment]
Ficou massa pra caramba :) mas vamos publicar só na próxima segunda, nos meus testes, publicar em uma segunda-feira é o que deu mais retorno. Segue um frame do vídeo:

![image](https://cloud.githubusercontent.com/assets/4248081/10191628/06a53c0a-674c-11e5-924a-304d1d628edd.png)

**Comment by ftonato** [comment]
Camisa legal o/
