### ISSUE TITLE
Nome do canal

### ISSUE THREAD

**Issue by ftonato** [filipedeschamps/javascriptmasters.com.br#172]
Já podemos customizar o nome do canal do Youtube?

**Comment by filipedeschamps** [comment]
Sim total :) ficou assim: https://www.youtube.com/c/JavascriptMasters

**Comment by ftonato** [comment]
Ah legal!
É que na index do site tem uma url p/ o canal, mas quando passei o mouse (hover), percebi que estava o nome com hash: *https://www.youtube.com/channel/UCU5JicSrEM5A63jkJ2QvGYw*

**Comment by filipedeschamps** [comment]
hmm será que é do widget do próprio Youtube?

**Comment by ftonato** [comment]
Talvez!

No arquivo [youtube-follow-widget.html](https://github.com/filipedeschamps/javascriptmasters.com.br/blob/gh-pages/_includes/youtube-follow-widget.html), temos o seguinte trecho de código:
```html
<script src="https://apis.google.com/js/platform.js"></script>
<div class="g-ytsubscribe" data-channelid="UCU5JicSrEM5A63jkJ2QvGYw" data-layout="full" data-count="default"></div>
````
Não poderíamos alterar o attr **data-channelid**?

**Comment by filipedeschamps** [comment]
Alterei, mas não funcionou, que pena :( olha como fica:

![image](https://cloud.githubusercontent.com/assets/4248081/10364369/07f486a6-6d91-11e5-8aba-893b2fae0716.png)

**Comment by ftonato** [comment]
Esses produtos da Google hahahaha :dancers:
