### ISSUE TITLE
Quando vai sair mais videos ?

### ISSUE THREAD

**Issue by wgoulart** [filipedeschamps/javascriptmasters.com.br#180]
Hey @filipedeschamps quando vai sair mais videos ? Estou curtindo bastante dos conteúdos que tu tem compartilhado. Parabéns !

**Comment by filipedeschamps** [comment]
Fala meu caro, tudo bem?

Obrigado pelo retorno :)

Estou louco para fazer mais vídeos, nestas últimas semanas o tempo apertou muito, estou trabalhando praticamente 3 turnos todos os dias, mas vai estabilizar :+1: 

Abração!
