### ISSUE TITLE
Adicionar mídias sociais

### ISSUE THREAD

**Issue by ftonato** [filipedeschamps/javascriptmasters.com.br#181]
Estava visitando o site e percebi que não há links p/ as redes sociais (**Twitter** / **Facebook**) fora das postagens.
O que acha de adicionar no rodapé do site?

/cc @filipedeschamps

**Comment by filipedeschamps** [comment]
Eu topo meu caro!

E que bom que você abriu essa issue, vou voltar a escrever para o blog novamente daqui a algumas semanas :+1:

**Comment by ftonato** [comment]
Legal mestre!

Ainda bem, estava preocupado com a falta de conteúdo interessante na minha vida hahaha
Aguardo pelas postagens :)

**Comment by ftonato** [comment]
Podemos abrir novamente a _issue_ se necessário.

Fico a disposição!
