### ISSUE TITLE
Por que parou?

### ISSUE THREAD

**Issue by luanrm** [filipedeschamps/javascriptmasters.com.br#194]
Parou o projeto do blog?

**Comment by filipedeschamps** [comment]
@luanrm tudo bem?

Muito obrigado pela issue :)

O blog acabou continuando por vídeo nesse canal (https://www.youtube.com/channel/UCU5JicSrEM5A63jkJ2QvGYw) mas mesmo assim o trabalho no Pagar.me está tão corrido que não sobra tempo ou cabeça para continuar com o canal por enquanto :(

**Comment by luanrm** [comment]
Deu muito certo o canal, sucesso @filipedeschamps !
