### ISSUE TITLE
Adicionar cadastro de Feed RSS

### ISSUE THREAD

**Issue by ftonato** [filipedeschamps/javascriptmasters.com.br#86]
Já pensou em criar um cadastro de Feed RSS?

Poderia usar o SendGrid para enviar os e-mails!

**Comment by filipedeschamps** [comment]
@ftonato tudo bem meu caro?

Esta é uma idéia fantástica! Você já teve experiência com o SendGrid? Saberia dizer as diferenças entre ele e o MailChimp?

**Comment by ftonato** [comment]
@filipedeschamps tudo certo, e por aí?

Pois bem, usei apenas o SendGrid uma vez p/ um teste básico (nodeJS), mas nunca em produção!

Procurei sobre a diferença, e pelo que diz no link que achei [How are SendGrid and MailChimp different?]  (http://www.quora.com/How-are-SendGrid-and-MailChimp-different ) creio que talvez nesse caso a melhor opção talvez seja MailChimp!

Tu também podes conversar com algum pessoal que usa essas ferramentas para tirar às dúvidas que surgirem e se precisares de ajuda para alguma coisa, me avise que serei grato em ajudar!

**Comment by ftonato** [comment]
E aí Filipe, blz?
Alguma novidade sobre essa *issue*?

**Comment by filipedeschamps** [comment]
@ftonato depois da sua issue eu olhei por cima o Mailchimp e parece ser a solução que precisamos mesmo. Não tive tempo de implementar ainda, mas com certeza será incluído.

A idéia seria o mais simples possível: colocar um link no menu apontando para uma página sobre a newsletter, e a pessoa faria o subscribe ali.

Se você tiver alguma disponibilidade de fazer um pull request com algum protótipo, seria extremamente bem vindo. Dai poderemos evoluir a idéia em cima disto.

Abração! :+1:

**Comment by ftonato** [comment]
@filipedeschamps estive navegando pelo sistema do Mailchimp, fiz alguns testes básicos e definitivamente é bem fácil administrar ;)

Sem muito esforço encontrei uma postagem do [tableless.com.br - Assinatura de newsletter com PHP integrada à API do Mailchimp!] (http://tableless.com.br/assinatura-de-newsletter-com-php-integrada-a-api-do-mailchimp/)

No fim da postagem tem a url com o [projeto aqui no github] (https://github.com/straube/mailchimp-sample-form)!

Já fez o cadastro lá no site?

**Comment by filipedeschamps** [comment]
Meu caro, acabei de criar a conta lá e estou em cima. Vou criar um form para o pessoal fazer subscribe :+1:

**Comment by ftonato** [comment]
Certo, fico no aguardo!
Se precisar de ajuda, me avise :+1:

**Comment by filipedeschamps** [comment]
@ftonato está no ar :)

Veja o que acha: https://www.javascriptmasters.com.br/

**Comment by ftonato** [comment]
@filipedeschamps legal, cadastrei-me inclusive =)

Tenho algumas sugestões que podem ser discutidas em outras issues:
O evento `:hover` do botão:"Assine a newsletter";
O evento `:hover` dos botões do modal da newsletter;
Validar o campo Email do modal da newsletter (pelo menos um != empty).

O que tu acha?
Se quiser eu crio as issues...

**Comment by filipedeschamps** [comment]
Ademílson, sensacional!

Se quiser contribuir mexendo no código também, seria de extrema valia!!! :)

Mas do contrário, as issues seriam extremamente bem vindas também meu caro!

Vamo que vamo!

2015-07-23 15:38 GMT-03:00 Ademílson F. Tonato <notifications@github.com>:

**Comment by ftonato** [comment]
Vou abrir essas issues e contribuir com os códigos ;)
Podes fechar essa já :dancers:

**Comment by filipedeschamps** [comment]
Shooooww!!!!
